const express = require('express')
const router = express.Router()
const addressController = require('../../controller/shared/addressController')
const validate = require('../../middleware/zodMiddleWare')
const addressValdiation = require('../../util/shared/addressValidation')
const  tokenMiddleware  = require('../../middleware/tokenMiddleware')
router.post("/address",validate(addressValdiation),addressController.addAddress)
router.put("/address/:id",addressController.updateAddressbyId)
router.get("/address",addressController.getAllAddress)
router.get("/address/:id",addressController.getAddressById)
router.delete("/address/:id",addressController.deleteAddressById)
module.exports = router 