const express = require('express')
const router = express.Router()
const userController = require('../../controller/customer/userController')
const validate = require('../../middleware/zodMiddleWare')
const userValidation = require('../../util/customer/userValidation')
// router.post("/user",validate.validate(userValidation),userController.addUser)
router.post("/user",userController.addUser)
router.put("/user/:id",userController.updateUserbyId)
router.get("/user",userController.getAllUsers)
router.delete("/user/:id",userController.deleteUserById)
module.exports = router 