const express = require('express')
const router = express.Router()
const supplierController = require('../../controller/supplier/supplierController')
const validate = require('../../middleware/zodMiddleWare')
const supplierValidation = require('../../util/supplier/supplierValidation')
router.post("/supplier",validate.validate(supplierValidation),supplierController.addSupplier)
router.put("/supplier/:id",supplierController.updateSupplierbyId)
router.get("/supplier",supplierController.getAllSupplier)
router.get("/supplier:/id",supplierController.getSupplierById)
router.delete("/supplier/:id",supplierController.deleteSupplierById)
module.exports = router 